### ISSUE TITLE
Desynching in MP

### ISSUE THREAD

**Issue by darkshadow1809** [veden/Rampant#1]
Whenever exploring biter bases or even remotely playing in MP we keep desynching with this mod. Is this mod multiplayer compatible or is it a big NO? For now I am calling it an issue.

Very severe one aswell. If you put
/c game.player.character = nil
and explore in MP you will get constant frequent desynch between other players.
Here's the mod list 

http://pastebin.com/aavB6cLv

Here's the modpack
https://www.dropbox.com/sh/4ll7q8pt2v5s654/AADj1iuj3H7D44bc_UDvydKda?dl=0

If you need anything else I'd like to hear from you!
Thanks in advance :-)

**Comment by veden** [comment]
Should be working for MP now
