### ISSUE TITLE
Pollution-caused nests obliteration

### ISSUE THREAD

**Issue by garrotte13** [veden/Rampant#100]
I don't know if this is by design or not
https://youtu.be/Ph5lxPFej3s

I have game map 50% and 50% modifiers of pollution absorption and attack cost (standard Deathworld settings). So it's a tricky game start for doubled tech costs and other mods resources requirements.

I didn't notice this problem before, because I always destroy biters nests in polluted areas ASAP no matter how much iron or iron/copper I pay for it. Now I can't do it due to another limitation I put.
And I see, that early game often goes to dead end if those biters hordes are converted into builders instead of raiding me.

Is it by design, that pollution-produced biters can be used for Siege attacks or other migrations ?

**Comment by veden** [comment]
Yes, it is by design. What behavior are expecting?

**Comment by garrotte13** [comment]
I didn't have any special expectations. But the moment when several hordes are sent to siege - it's a gorgeous dead end. And probably this is how it must be.
It's not a stupid vanilla and all videos of this guy he made in several years of game experience with his "how-to" are useless with Rampant
https://www.youtube.com/watch?v=PopwHsrKNd4
muaha-ha-ha...
