### ISSUE TITLE
Ticking Error

### ISSUE THREAD

**Issue by Mattpenguin** [veden/Rampant#11]
Upon updating to Rampant version 0.16.3 I received the following error on both a headless server and a single player save (Factorio version 0.16.18) :

Error while running event Rampant::on_tick (ID 0)
__Rampant__/libs/AIPlanning.lua:56: attempt to perform arithmetic on upvalue 'AI_MAX_SQUAD_COUNT' (a nil value)

By the looks, the 'isShockwaveReady' function appears to still be using the AI_MAX_SQUAD_COUNT value that was being deprecated/removed last patch.

I was able to temporarily work around the issue by editing Constants.lua and uncommenting the constants.MAX_SQUAD_COUNT line.

If any additional Information is needed (Testing steps, other mods, etc.) let me know

**Comment by veden** [comment]
thanks for the report. this should be fixed in the latest build

**Comment by Mattpenguin** [comment]
The issue indeed appears to be fixed. Thanks for the quick patch!
