### ISSUE TITLE
Rampant uses about 6 GB of ram by itself.

### ISSUE THREAD

**Issue by staviq** [veden/Rampant#13]
Yes, thats 6 Gigabytes.

Vanilla no mods, about 2 GB of ram usage.

Rampant enabled, 7-8 GB of ram in the main menu, before the game ist even started ???

**Comment by Mattpenguin** [comment]
Until the issue is properly fixed, a workaround is to disable the new enemies that Rampant adds.

Options -> Mod settings
Under the start up tab, scroll to Rampant's configuration section and uncheck the box next to "Enable new enemies"

**Comment by veden** [comment]
It is due to all of the unit images, the next build will have a limited version

**Comment by veden** [comment]
the default is off now, and a slider to adjust the number of variations per tier. Currently for the new enemies a minimum of 2GB of extra is RAM required.

**Comment by staviq** [comment]
Alright, so i removed any stored settings from mod-settings.json and updated to 0.16.8 and it's waaaay bettrer now, with about 3.6GB of ram in the main menu, and about 5GB in-game.

At least it's playable now, as previously the game crashed every time i tried to load a save.

Thanks guys.
