### ISSUE TITLE
AI_STATE_PEACEFUL causes biters to bank points

### ISSUE THREAD

**Issue by Dagothur** [veden/Rampant#131]
To my understanding AI_STATE_PEACEFUL allows the biters to accumulate a large point bank as the AI does not spend during this state. Presumably this should result in a surge of activity once AI_STATE_PEACEFUL ends. An argument could be made that AI_STATE_PEACEFUL is increasing the difficulty of a playthrough which is the opposite of what its name suggests.

The state could either be reworked or reworded. Some ideas:

1) Mitigate the point surge:
-Prevent biters from gaining points and/or
-Cause them to gain points at a reduced rate and/or
-Passively reduce their points each logic cycle

2) The state could be renamed (e.g. AI_STATE_SWARMING) and a description could be added outlining this behavior

**Comment by veden** [comment]
Do you have a preference?

**Comment by Dagothur** [comment]
No personal preference as we play with peaceful disabled. I think the best solution would be to disable biters from gaining points during this state which should stay true to the intention of AI_STATE_PEACEFUL giving the player some breathing room.

(The biters going dormant/swarming to build up a large attack could be an interesting mechanic but would require care to implement in such a way that feels fair. Something like scaling the point build up based on evolution and also choreographing the attack in some way such as with chat messages.).

**Comment by Dagothur** [comment]
#132 should make it easy to implement this.
