### ISSUE TITLE
Tier reduction from 10 to 6 discussion

### ISSUE THREAD

**Issue by Dagothur** [veden/Rampant#133]
I wasn't sure where or how to start a discussion on this so I did it here.

What is the intention with reducing the number of tiers? Over the last few weeks we were actually thinking about asking you to add a few more so that Rampant could scale a little better into the mid and late game.

**Comment by veden** [comment]
May also be ways to reduce entity counts through scripting or entity reuse.

**Comment by Dagothur** [comment]
Is what's happening in the video a known issue? Do you know if it's been documented or discussed anywhere? My gut instinct is that the user has a low end system (?).

We always play with variations set to 1. 

What we are finding is that if we can get out of the early game (which is always challenging and the most fun imo) then often we do not feel like the biters could break us in the mid to late. We thought maybe if the biters kept scaling (T11, T12 ...) that it could help with this.

**Comment by veden** [comment]
Not sure about a known issue, haven't reported it to the factorio devs.
I was able to reproduce this issue and I don't consider my machine to be on the low end of systems.

Do you set the enemy level higher then the default of 6?

**Comment by Dagothur** [comment]
Yes, we set it to 10 with all factions enabled. 

I tried again with variations set to 20 and was able to get it to occur.

**Comment by veden** [comment]
if there were to be extra tiers at what evo would they appear?

**Comment by Dagothur** [comment]
Overall the first 5-6 tiers feel well paced and challenging. 

Possibly T11 could start where T10 is now, pushing T10 a little earlier and compressing the prior tiers (6, 7, 8, 9).

**Comment by garrotte13** [comment]
Variations is a nice thing (not 10 of course, but 2-3 is what I always use to see some randomness of entities health/attack range/resistances - makes game more realistic and interesting, when some worm can hit harder, but with less range than its predecessor).

Reducing tiers for player number is a bad idea in general. May be there is some other way to reduce entities number. Like replacing/upshifting properties for low tiers somehow. Low tiers entities are absolutely useless after tiers 8..10 come into play.

**Comment by veden** [comment]
I may re-add variations as an option with a lower cap.
I can't think of a way to reduce upper and lower tiers based on evolution because the entities are created during game startup.

**Comment by garrotte13** [comment]
> IhVy0c.mp4
> 
> When lots of entities are loaded into factorio this is the effect that starts to happen.
> 
> So I removed the variations options and reduced the number of tiers present in a game.
> 
> Other options are removing or consolidating factions and potentially adding a mod setting to adjust the number of tiers present.
> 
> The problem with mod options is it tends to make the code more complex and less likely that I've tested all the codepaths.
> 
> With more tiers does that include enemy structures or just units?

I can't reproduce this effect ( I did create blueprint with one pole and multiplied 300 ghosts in 3 seconds like he did - no problems, UPS = 60, no slow down). I don't know what mods video creator added besides Rampant. Should I have explored huge map with thousand of nests? I do remember this post somewhere, but can't find it now.

**Comment by veden** [comment]
setting variations to 20 with new enemies enabled should make the slow down much more evident

**Comment by veden** [comment]
I've re-added the variations setting and set the max to 7.
