### ISSUE TITLE
Team-based multiplayer failed to load

### ISSUE THREAD

**Issue by OvermindDL1** [veden/Rampant#14]
States that the event handlers differed between client and server.  Remember that if an even handler is registered then register it at the start and never unregister it.  To no-op it set it to a different empty-bodied function instead of unregistering it.

**Comment by veden** [comment]
As far as I know I'm not conditionally unregistering anything

**Comment by OvermindDL1** [comment]
Are they registered at any time other than start-up?

**Comment by veden** [comment]
no

**Comment by OvermindDL1** [comment]
How funky...  ^.^;

**Comment by veden** [comment]
are still having this issue?

**Comment by OvermindDL1** [comment]
Haven't tried it on a server yet, I'll have to grab someone to test, might can do so tonight (ping me if you get this before then by just mentioning my name like @OvermindDL1 and I'll use that as a reminder.  :-) ).

**Comment by daxpedda** [comment]
I'm playinig multiplayer every day, no issus so far.
However I'm not sure I understand the conditions of this bug, if somebody can explain it to me I can test it.

**Comment by OvermindDL1** [comment]
> I'm playinig multiplayer every day, no issus so far.
> However I'm not sure I understand the conditions of this bug, if somebody can explain it to me I can test it.

You have to be playing multiplayer on different teams, I.E. you need to be playing a scenario (there is a built in pvp scenario for example) or a mod that has players be on different teams.
