### ISSUE TITLE
Crash related to nil mergeGroup/unitGroup in UnitGroupUtils.lua

### ISSUE THREAD

**Issue by tmarki** [veden/Rampant#16]
Getting a crash on the latest version of Factorio/Rampant, a few seconds after loading a savegame.

Error while running event Rampant::on_tick (ID 0)
__Rampant__/libs/UnitGroupUtils.lua:211: attempt to index local 'mergeGroup' (a nil value)

I did fix it by removing the new enemies setting and reloading the game (this made all the enemy bases disappear), but it started to happen a few hours after this again (after re-enabling the new enemies, they're too much fun).

**Comment by tmarki** [comment]
I changed the following code:

```
    if mergeSquad ~= squad then

        local mergeGroup = mergeSquad.group
        if mergeGroup == nil then
            player.print("IT HAPPENED")
        end
        if mergeGroup ~= nil and mergeGroup.valid and (euclideanDistanceNamed(position, mergeGroup.position) < GROUP_MERGE_DISTANCE) and (mergeSquad.status == status) and not isAttacking(mergeGroup) then

```

So that it would print out "IT HAPPENED", and loaded up the save where the crash occurred. Strangely nothing so far...

**Comment by veden** [comment]
single or multi player?

**Comment by tmarki** [comment]
Single player.

**Comment by veden** [comment]
the next build should have some guards against this, but if you come up with a save that has this happen, please post it here

**Comment by tmarki** [comment]
Will do, thanks!

**Comment by tmarki** [comment]
It seems like it's pretty hard to reproduce, as it's not deterministic and depends on what I do.

However, by saving frequently I managed to produce a save that will produce a similar, probably related error.

It's quite large, so I uploaded it to [my server](http://tmarki.com/Feb2018-rampant.zip). Just load it up and don't do anything, the crash will happen at playtime 1 day, 10 hours and 7 minutes.
The error will be:
```
Error while running event Rampant::on_entity_died (ID 4)
__Rampant__/libs/UnitGroupUtils.lua:70: attempt to index local 'unitGroup' (a nil value)
```

(Screenshot)[http://tmarki.com/rampartcrash.jpg]

Other mods I have loaded:

- Alien biomes
- Bottleneck
- EvoGUI
- New Game+
- Resource Spawner Overhaul
- Upgrade Builder and Planner

I hope this helps.

**Comment by veden** [comment]
I noticed that when I loaded up your save that the version was 0.16.14, please try the latest version and let me know if the issue persists.

**Comment by tmarki** [comment]
The save was done with the latest alpha of Factorio, but the run was started under that version I guess.

**Comment by veden** [comment]
0.16.14 being the version of rampant you are running and the latest being 0.16.19

**Comment by tmarki** [comment]
Ah, sorry - I will update it and wait for the crash to happen (or not). The reason was that I manually patched it and used that version, and it ran without problems.
 Thanks anyway.
