### ISSUE TITLE
new, more advanced factions appearance after Rampant3.2 upgrade

### ISSUE THREAD

**Issue by garrotte13** [veden/Rampant#166]
After upgrading Rampant3.2 from sources version 6ac708377399a1a3c2abe03ae32efc107783b047
to version
1830611a00019314bcbfa6e3c5fe2d80e58dcd44
I found out that one or two of clans (more friendly in-game name for Bases) became a mix of Poison and Laser factions. Instead of Acid faction. I have a gamesave (saved before code update) or can make a video. And those two factions are expanding in that area through structures upgrade replacing Common and Acid.
Evolution level is 29%, which I believe is too low for both of these early endgame factions (expecting Laser after 45%, expecting Poison somewhere near 60%).

I returned to old save where I upgraded and found that after returning to old sources I see only Acid faction structures in that area.

**Comment by veden** [comment]
Both Laser and Poison can start showing up after 26% evo. Typically you don't see them that early because the clans have already been established by that time.

**Comment by garrotte13** [comment]
So you mean that normally player doesn't encounter those factions so early, because already finishes nearest areas discovery before evolution reaches 20%, therefore more advanced exploration or mutations events are required after evo 26%. Specific situation with unexpected clans re-setup. But then I don't understand how it could happen that a huge number of nests and worms changed faction from Common/Acid to Laser/Poision. They (those structures in chunks) were generated before code update.

**Comment by veden** [comment]
the 3.2.0 update wiped all map data and re-setup the map which would cause all existing clans to be re-rolled for factions.

**Comment by garrotte13** [comment]
Ok.
