### ISSUE TITLE
After updating from 3.1.2 to 3.2.0 (or higher) biters drop landfill on death when they are killed close to the water

### ISSUE THREAD

**Issue by jigsaw3xD** [veden/Rampant#170]
Evolution 0.9766, playing with Space Exploration. When turning off Rampant (or downgrading to 3.1.2) the issue disappears. The landfill placement seem to be triggered by biter's remains that fly off on animation death.

https://user-images.githubusercontent.com/130259215/230748495-a482da86-2988-42f7-8a5d-0ec3ae0da00a.mp4

**Comment by veden** [comment]
Working as expected. Can be turned off in the mod settings.
https://github.com/veden/Rampant/blob/master/changelog.txt#L68

**Comment by jigsaw3xD** [comment]
> Working as expected. Can be turned off in the mod settings. https://github.com/veden/Rampant/blob/master/changelog.txt#L68

Oh, shoot. Sorry, I searched the changelog page and mod settings for "landfill" but couldn't find a line with it. Thanks for the quick response.
