### ISSUE TITLE
After decompressing and hesitating to attack an entire group of biters sometimes disappear from the game

### ISSUE THREAD

**Issue by jigsaw3xD** [veden/Rampant#171]
I was able to make a save right before a group of biters disappear (consistently) and can upload it if needed (it's a Space Exploration playthrough with lots of other mods tho none of them are enemy-related except for Rampant). I'm not 100% sure if decompressing and hesitating are actually relevant to this bug but those were conditions under which bug occurred several times in my playthrough.

Their "hesitation status" (when they either just stand there or move towards very slowly) seem to be very wonky as well with biters compressing/decompressing several times near player entities (walls/turrets) and sometimes getting killed while being compressed (tho this happens rarely and very hard to capture on video).

https://user-images.githubusercontent.com/130259215/230954960-b7626e1a-1643-47c1-b90b-fabfe23f493c.mp4

**Comment by jigsaw3xD** [comment]
I was able to make a save right before a group of biters disappears (consistently) and can upload it if needed.

**Comment by veden** [comment]
The group disappearing is due to the squad cleanup logic.

Can you provide a save?

**Comment by jigsaw3xD** [comment]
> The group disappearing is due to the squad cleanup logic.
> 
> Can you provide a save?

https://drive.google.com/file/d/1SnvkTFaDIoeq0WTMj7TUM2fHPJVKD_wR/view?usp=share_link

**Comment by veden** [comment]
This is the current issue that I'm looking into.

**Comment by garrotte13** [comment]
Has the same issue with squads disappearing after several retreats.
By the way what is the goal of retreating? To low AOE defenses effectiveness? It makes biters much more vulnerable against single-target turrets.

**Comment by garrotte13** [comment]
Found one more retreat effect - defending (revenging?) biters squad is much more difficult to kite out of enemy base closer to my turrets. Fun!
