### ISSUE TITLE
Groups of biters appearing in the middle of water / not doing anything (just compressing and decompressing) / running back

### ISSUE THREAD

**Issue by jigsaw3xD** [veden/Rampant#172]
![qvsaSDJnQC](https://user-images.githubusercontent.com/130259215/232058682-c3040631-c7cc-47a4-8de3-b56f2a752423.jpg)

All in one screenshot. On the same save as I've shared in prev topic.

**Comment by veden** [comment]
This should be fixed in the upcoming version
