### ISSUE TITLE
Most NE units not being spawned

### ISSUE THREAD

**Issue by plague006** [veden/Rampant#18]
A few times are present: mutated and infected biters, but the others are not.

This is with:
Factorio 16.51
NE Enemies 9.0.10
Rampant 0.16.34

Testing methodology:
Install both mods, start a new world with default settings to ensure NE is working as expected.

Turn on "World: Enable new enemies" option and restart.

Create new world, change evolution, nil your character, fly and see what's being spawned.

**Comment by veden** [comment]
I'm seeing a different issue about nest level, it may be related.

**Comment by veden** [comment]
This should be fixed in 0.16.35

**Comment by plague006** [comment]
Didn't see the pending feedback tag as that came after your comment. With 0.17 coming I don't think I'll have time to re-test before it drops.
GL with the transition. :)
