### ISSUE TITLE
Error: v0.16.37 > event Rampant::on_nth_tick(41)

### ISSUE THREAD

**Issue by Tosarius** [veden/Rampant#19]
Error while running event Rampant::on_nth_tick(41)
__Rampant__/libs/SquadAttack.lua:88: attempt to compare number with nil

Got this error in the current version (0.16.37) everytime I'm loading my savegame.

**Comment by veden** [comment]
Do you have a save that I can look at?

**Comment by veden** [comment]
nevermind, got one

**Comment by veden** [comment]
this should be fixed now

**Comment by Tosarius** [comment]
Seems fixed! Thank you.
