### ISSUE TITLE
AI stuck attacking indestructible structure

### ISSUE THREAD

**Issue by avosirenfal** [veden/Rampant#2]
Using Rampant, PredictabowlEnemies, and LightedElectricPoles (https://mods.factorio.com/mods/lettherebelight/LightedElectricPoles) I've occasionally seen massive growing waves of aliens stuck attacking the 'poles'. I'm guessing they're actually attacking the indestructible/off-grid/invisible lamps the mod uses to do the lighting.

I poked around in Rampant but it appears the vanilla game does all the actual attack logic, and you just decide when to spawn waves/move them around? What might be the problem here?

**Comment by avosirenfal** [comment]
Props on the mod by the way, this is by far the best thing I've seen, despite having ~60 mods in our modpack. The game really needed it.

**Comment by veden** [comment]
Thanks, always nice to hear people enjoy this.

There is a small chance when a group spawns that it will attack anything and everything it finds (that is the rabid in the code). Also when the natives enter combat or a certain distance from the player they frenzy for a set radius in which they attack everything. 

So, if the problem only occurs with Rampant and the LightedElectricPoles then the above is my guess as to the initial cause.

I quickly looked through the light poles mod and I'm not seeing anything that sets them to indestructible (the flag on the entity, a zero health, or resistances).

You are correct about the vanilla game handling the actual attacking as it does it much faster than I can in lua.

At one time Natural Evolution was doing an indestructible rail and I had wrote some code to replace using indestructible items with something that replaced itself on death and forced enemies around the item to wander off. 
https://github.com/veden/Natural_Evolution_Modules/commits/master
the commits on July 27, 2016.

**Comment by avosirenfal** [comment]
The indestructible flag is set here on the invisible lamps here: https://github.com/lettherebelight/lighted-electric-poles/blob/master/control.lua#L13

Would setting the lamps to a different force help? I guess I could set the lamps to be owned by the alien's force, but I'm not sure how to get a reference to the alien force or whether that's likely to break anything else.

**Comment by avosirenfal** [comment]
Yeah, I'm just going to try setting the lamps to game.forces['enemy']

**Comment by veden** [comment]
Completely missed that. 

I don't know if it will cause issues with picking things up, but give it a shot.
