### ISSUE TITLE
Error: v0.16.38 > event Rampant::on_nth_tick(41)

### ISSUE THREAD

**Issue by Tosarius** [veden/Rampant#20]
Occurs (like the one before) on loading the game.

Error while running event Rampant::on_nth_tick(41)
__Rampant__/libs/SquadAttack.lua:96: attempt to perform arithmetic on field '?' (a nil value)

Link to the savegame: https://www.dropbox.com/s/3s944lifudry89b/04.zip?dl=0

**Comment by veden** [comment]
Thanks for the report, I will look later today.

**Comment by veden** [comment]
This should be fixed in the latest

**Comment by Tosarius** [comment]
can now load the savegame.
thank you!

**Comment by NetTecture** [comment]
@veden Got stuck with that today, had to remove rampant to play on. Happens now around a quarter second or so after loading.

**Comment by Tosarius** [comment]
@NetTecture Can't reproduce that in v0.16.39, my savegames load fine.
