### ISSUE TITLE
bugs on water

### ISSUE THREAD

**Issue by asomedude9897** [veden/Rampant#21]
is there a way or a place to disable the new bugs from your mod to stop crossing water tiles

**Comment by veden** [comment]
Can you give more information as I don't believe they should be crossing water tiles.

**Comment by asomedude9897** [comment]
they are crossing water tiles as they chase me in my helicopter

**Comment by asomedude9897** [comment]
[https://media.discordapp.net/attachments/231518135231053825/563502811531182090/here.PNG?width=309&height=375](url)

**Comment by asomedude9897** [comment]
i just want to know if its this mod or another.  i am starting here because this really only started when i turned on new enemies.  and i don't have any other mods that really change the way the bugs work in factorio.

**Comment by asomedude9897** [comment]
ive been dooing testing and have found only the new classes can traverse water

**Comment by veden** [comment]
do you have noxys swimming mod?

**Comment by asomedude9897** [comment]
no

**Comment by asomedude9897** [comment]
can you see the image i linked

**Comment by veden** [comment]
Yes, what is your modlist?

Unless something recently changed internally in factorio the new enemies shouldn't be running on water

**Comment by asomedude9897** [comment]
this is rampant v 16.42 
and my mod list is here 
https://pastebin.com/eHa8E2XU

**Comment by veden** [comment]
my guess it is the hovercraft mod

**Comment by asomedude9897** [comment]
ill try it now

**Comment by asomedude9897** [comment]
yep it was the hovercraft mod
any ideas why

**Comment by veden** [comment]
Changes to the water tiles collision mask not making it onto the new units correctly.

Something to bring up to the hovercraft mod author

**Comment by asomedude9897** [comment]
thanks for your help will do

**Comment by asomedude9897** [comment]
where should i leave a message for him
forums

**Comment by veden** [comment]
https://mods.factorio.com/mod/Hovercrafts

**Comment by veden** [comment]
https://mods.factorio.com/mod/Hovercraft

**Comment by veden** [comment]
I didn't realize there are two

**Comment by asomedude9897** [comment]
its not letting me its saying that 
"We are sorry, but you are not authorised to use this feature. You may have just registered here and may need to participate more in discussions to be able to use this feature."

**Comment by veden** [comment]
https://mods.factorio.com/mod/Hovercraft/discussion?
https://mods.factorio.com/mod/Hovercrafts/discussion?

if you are using the top mod, it says in the changelog that 0.0.7 fixed the unit issue with Rampant.
