### ISSUE TITLE
Unit groups freeze

### ISSUE THREAD

**Issue by melinstagibson** [veden/Rampant#23]
So for some reasons some of the unit groups, especially when there are alot in total just freeze on the spot and wont move for several minutes. I cant really figure out how this happens but the debug mode shows no target for those units.
there are also newly spawned units that become part of that group and they move just fine but the main chunk of the group stays frozen.
im playing factorio 0.17.x, no other mods messing with AI enabled

**Comment by veden** [comment]
I get what your saying, but it isn't enough for me to diagnose the issue.

I would need a save at the least.

**Comment by AdrianShepard** [comment]
I had same problem today, playing on 0.18.18
Map was complex and had a lot of islands,i noticed sometimes bugs would freeze and just stand doing nothing

Mods used:
![image](https://user-images.githubusercontent.com/43182805/79673677-75606680-81e4-11ea-98be-a60fa7b0fed6.png)
My save file
[111.zip](https://github.com/veden/Rampant/files/4498011/111.zip)

**Comment by veden** [comment]
Are you still having this issue in the latest version of Rampant?
