### ISSUE TITLE
Multiplayer desync: desync reports reveal "ImpassableChunk"s that shouldn't be there.

### ISSUE THREAD

**Issue by jnshi** [veden/Rampant#27]
A server I play on has had our players repeatedly experience desync-on-loads.

While diffing the script.dat files from one of the desync reports, the only thing that stood out was a squad that had a "ImpassableChunk" as one of its movement penalities on the local copy.

<img width="661" alt="factoriodesyncimpassablechunk" src="https://user-images.githubusercontent.com/3675380/82029773-bdfe2900-9697-11ea-80d3-45acb411d16f.PNG">

I looked through the code trying to figure out how this could've happened, and it seemed impossible, as every single `addMovementPenalty(squad, chunk)` is conditioned on an `if (chunk ~= SENTINEL_IMPASSABLE_CHUNK)`. The only way I can think of as to how an impassable chunk can still end up as a movement penalty is if there is more than one "ImpassableChunk" object lurking on the heap, as `~=` is a comparison by reference. Maybe the two objects arise in this manner: one from the Constants.lua file, and one from deserialization of the server game state. But I don't know where/how deserialization happens, so this was as far as I was able to investigate.

Here's a copy of the full desync report:
[https://drive.google.com/file/d/1N7uTs0Ol91rxxzMocb0YTvducM_j24Gi/view?usp=sharing](url)

I looked through a few other desync reports from the same game and could find others with differences in "ImpassableChunk"s.

**Comment by veden** [comment]
Hadn't seen this before. Thanks for putting in the time to find this.

**Comment by veden** [comment]
are you still having this issue with the latest build?
