### ISSUE TITLE
Sprite Size/Alignment Issue Crashes Game

### ISSUE THREAD

**Issue by PlatinumFrog** [veden/Rampant#30]
![factorioerror](https://user-images.githubusercontent.com/4785824/88990957-5c6c5480-d2ad-11ea-80ff-8ddcbaef7529.png)
Probably due to the revising of various sprites in the new 0.18.x updates. Sorry if this is already known. Factorio Log: 
[factorio-current.log](https://github.com/veden/Rampant/files/5004609/factorio-current.log)

**Comment by NetTecture** [comment]
The ARampant mod portal discussion forum has various issues for this including the solutions at https://mods.factorio.com/mod/Rampant/discussion

Would be onderfull if somoene could make a PR and then Veden could reissue a fixed version. We also are hitting 1.0 release VERY soon ;) This is a core piece for many.

**Comment by veden** [comment]
should be fixed in the latest.

**Comment by PlatinumFrog** [comment]
@NetTecture Yes, I was browsing those discussions, and came across those fixes and applied one. 
@veden I just saw that the mod was updated and so I uninstalled the modified version of Rampant and reinstalled Rampant for the new version. The update fixed the issue. Thank you Veden.
