### ISSUE TITLE
Feature request: converting Rampart into a scenario soft mod

### ISSUE THREAD

**Issue by guppyfaced** [veden/Rampant#36]
Hi!

Love the mod and the creativity behind it.

I'm part of a community called 'Biter Battles' where two teams indirectly attempt to destroy each other by sending science to increase the evolution of the biters attacking.

However, we are facing two problems: the biters are stupid and secondly, pathing biters are incredibly cpu hungry which causes the game to lag.

I am hopeful that your mod would solve these problems. Merging it into the existing scenario would be challenging as we don't plan to add any "hard" mods but I am hopeful, that with assistance, we could incorporate your solutions into a scenario.

**Comment by veden** [comment]
I can't say that Rampant will make the Pathing much better, typically the added units group offset any potential speedup you may see.
As for the first one, Rampant should make them a threat.
I looked at a quick video of biter battles and it looks like you have multiple enemy forces that have different evolution.
If that is the case then Rampant will need adjustment around what are enemy forces as it currently always assumes a single enemy force called enemy.
I've never made a scenario, so I'm not sure what that entails.

**Comment by guppyfaced** [comment]
I have been using your code as a reference for improving pathfinding using the parameters in map settings, such as cache and maximum steps to search, as the map is only 512 blocks wide. 

Pathing, reducing the biter hitbox, the pheromone system and the biter tactics are modifications of mostly existing functions or scripts that can be run as a scenario. At least, that's what I think.

To add sprites or sounds would require a mod.

If it's possible to add the changes in stages, focusing on tweaking map settings first, editing vanilla biters behaviour and then adding the different types using existing assets with different skins.

**Comment by veden** [comment]
Do you have a video of a biter battle so I know what you are talking about?
