### ISSUE TITLE
Multiplayer desync with ONLY Rampant mod enabled, 5 seconds after joining the server for any player

### ISSUE THREAD

**Issue by grumd** [veden/Rampant#37]
Save: [_autosave4.zip](https://github.com/veden/Rampant/files/5997894/_autosave4.zip)
mod-settings.dat (zipped): [mod-settings.zip](https://github.com/veden/Rampant/files/5997896/mod-settings.zip)
Rampant 1.0.1 and **nothing else** enabled on the server.
Factorio 1.1.21 stable.

Desync doesn't happen on the same save if I just disable Rampant.

Desync report: 
[desync-report-2021-02-17_20-41-37.zip](https://github.com/veden/Rampant/files/5997903/desync-report-2021-02-17_20-41-37.zip)

Really wanted to try this awesome mod with my friends in a multiplayer game but it's not playable, desyncs instantly when joining the game :(

If you need any information or help to reproduce the issue, please just ask me.

I could do a small donation if you don't feel like supporting this mod for free.

**Comment by veden** [comment]
The next patch has a couple of desync fixes coming.

It may be a week or more before it gets published though.

**Comment by grumd** [comment]
I see, thanks for replying!

**Comment by veden** [comment]
Should be fixed in 1.0.3

**Comment by grumd** [comment]
Just updated to 1.0.4, seems to work fine! Thank you. I'll report back when I get to play a full session with friends too.

**Comment by grumd** [comment]
@veden Worked fine for quite some time with 1.0.4, but encountered another desync after playing for an hour or so. Got it to reproduce on a save only using Rampant.

desync report: https://puu.sh/HlgKm/38b308035e.zip
save: [_autosave9.zip](https://github.com/veden/Rampant/files/6064096/_autosave9.zip)
mod-settings.dat: [mod-settings.zip](https://github.com/veden/Rampant/files/6064100/mod-settings.zip)

**Comment by veden** [comment]
Yes, I was able to get a desync to happen.

Haven't had time to determine how to fix it.

**Comment by veden** [comment]
[Rampant_1.0.5.zip](https://github.com/veden/Rampant/files/6135467/Rampant_1.0.5.zip)
A copy of the mod that has all the hooks disabled that allow Rampant to interact with the game.
Still desyncs at ~7861188.
The mod version turns the game speed up to 7 until tick 7861000 then it turns the speed to 0.5

I don't think this is a Rampant thing to fix. The sub-forum for desyncs with mods doesn't seem to allow new topics, so currently this is a dead end for me.

**Comment by grumd** [comment]
Do you think this wouldn't be an issue if the save was started with Rampant enabled? I only added this mod later into the game. Or maybe if I regenerated all the terrain and biters it would help?

How different is this 1.0.5 version from the base version? You said you disabled all the hooks, but I'm not sure how this affects gameplay, which features does this remove?

**Comment by veden** [comment]
No, when you added Rampant wouldn't matter.

My guess is that it has something to do with Hives and spawning non-unit entities, but I'm guessing and don't really have any idea.

That 1.0.5 pretty much has the control.lua disabled in that Rampant wont make unit groups, move them, upgrade or build bases, change AI states and/or process the pheromone map.

Literally the only thing that 1.0.5 does is the prototype changes for things like new enemies otherwise the logic is completely disabled.

The purpose is to narrow down what is causing the desync, but as far as I can tell, I disabled the lua parts that could desync within Rampant and the desync still happens.

Just to be clear, that 1.0.5 build removes 99% of Rampant features and the desync still happens.

**Comment by veden** [comment]
My only thought currently is to try without the new enemies.

**Comment by bghira** [comment]
you have to report the thread to moderators with the request to move to desyncs with mods forum.

**Comment by axaluss** [comment]
What's up with the desyncs? Were they located and fixed?

**Comment by SneakyB** [comment]
Hello,
is there any info about strange desyncs? I have the same problem after killing all monsters it is working quite well, but after some time and evolution desync happend - strange is that 1 player dont have this problem and 2 players got it all the time, we tested with only rampart(newest version) and still happend for now it makes our server unplayable with mod.

**Comment by veden** [comment]
another attempt at fixing the desyncs is on master branch

**Comment by veden** [comment]
2.0.0 was released yesterday with a potential desync fix.
Please let me know if you are still having desyncs.

**Comment by PlexPt** [comment]
local variables will not saved to saves, so avoid to use local

**Comment by veden** [comment]
do you have a location that local variables are being used that needs to be corrected?

**Comment by PlexPt** [comment]
please check https://wiki.factorio.com/Tutorial:Modding_tutorial/Gangsir#Multiplayer_and_desyncs

**Comment by veden** [comment]
I meant in the code. I've read the tutorial before.

**Comment by veden** [comment]
3.1.0 should have a desync fix, please let me know if you are still having problems
