### ISSUE TITLE
Server crash : attempt to index field 'groupNumberToSquad' (a nil value)

### ISSUE THREAD

**Issue by Jupotter** [veden/Rampant#39]
Hello,

I was setting up a headless linux server with a few mods when I found a crash caused (seemingly) by Rampant.

after a few minutes of the server running, with a player logged in, the server crash with the following error:

```
factorio_1  | 1628.549 Error MainLoop.cpp:1285: Exception at tick 267157: The mod Rampant (1.0.3) caused a non-recoverable error.
factorio_1  | Please report this error to the mod author.
factorio_1  |
factorio_1  | Error while running event Rampant::on_unit_group_created (ID 135)
factorio_1  | __Rampant__/control.lua:827: attempt to index field 'groupNumberToSquad' (a nil value)
factorio_1  | stack traceback:
factorio_1  |   __Rampant__/control.lua:827: in function <__Rampant__/control.lua:783>
factorio_1  | 1628.549 Error ServerMultiplayerManager.cpp:91: MultiplayerManager failed: "The mod Rampant (1.0.3) caused a non-recoverable error.
factorio_1  | Please report this error to the mod author.
factorio_1  |
factorio_1  | Error while running event Rampant::on_unit_group_created (ID 135)
factorio_1  | __Rampant__/control.lua:827: attempt to index field 'groupNumberToSquad' (a nil value)
factorio_1  | stack traceback:
factorio_1  |   __Rampant__/control.lua:827: in function <__Rampant__/control.lua:783>"
```

Here are an autosave from the map, and the mod list/settings used

[autosave before crash.zip](https://github.com/veden/Rampant/files/6056862/autosave.before.crash.zip)
[mod list and settings.zip](https://github.com/veden/Rampant/files/6056864/mod.list.and.settings.zip)

The map is newly generated and only one player was connected. I was trying to trigger an attack wave by generating polution with the editor to reproduce the issue.

Notable mods used include:
- Space exploration
- Alien Biomes
- Factorissimo
- Armored Bitters
- Combat Mechanics Overhaul

**Comment by veden** [comment]
Thanks for the report, should be fixed in the latest

**Comment by Jupotter** [comment]
No error after running the server for ~2h, it seems to be fixed.

Thanks for the quick update!
