### ISSUE TITLE
Possible Performance Issue

### ISSUE THREAD

**Issue by AesSedai** [veden/Rampant#4]
I started a new save when Factorio 0.15.x was released, and modified the settings to be a combination of the Rail World + Death World presets (I like a very aggressive biter presence). Map view:

![screenshot_151](https://user-images.githubusercontent.com/7980540/27460104-6d941fe0-5777-11e7-9f1e-27bd5c1c15bc.png)

Recently (around the release of ~0.15.20), we've been experiencing periodic slowdowns of the game. We played with Rampant on Factorio 0.14.x and experienced massive slowdowns later into the game but they were more persistent than the slowdowns we've been experiencing in 0.15.x. Every 3-5 minutes or so, FPS and UPS both will drop from 60 to lower 20s - 30s and this will persist for anywhere from 10 - 45 seconds, usually. 

We've come to the conclusion that it's possibly related to biter attack waves. While the script update time for Rampant doesn't increase over 1ms during these slowdowns, the Entity update time usually reaches 40ms and has spiked to over 80ms before. The slowdowns appear to happen when the biters reach the engagement range of our turret defenses:

![screenshot_153](https://user-images.githubusercontent.com/7980540/27460208-0284ea6c-5778-11e7-90ec-964bd8b82e26.png)

Given the density of biters on our save and the level of evolution, we almost always have at least one attack wave incoming, but when multiple waves hit at the same time the game starts to crawl.

I've uploaded the save + mods to [Google Drive](https://drive.google.com/open?id=0ByjNoH5l8fatWV81bUNGLU1mN0U) for testing, but I'm not certain that the issue can be resolved from your end since it appears to be Factorio's entity handling code that is suffering under the stress.

Thanks.

**Comment by veden** [comment]
Yea, that sounds about right for when the slowdowns take place.
I loaded up your save and seemed to be getting at least 52.
You are correct in that this is starting to be a Factorio limitation.

One way to combat this is to buff the units in some way, so less units are needed to pose roughly the same threat.

**Comment by AesSedai** [comment]
Yeah, it's getting worse as we expand more and have a larger 'surface area' of wall to defend. 
A couple of ideas for reducing the number of enemies:

1) Add a level of biter above Behemoth and factor in its cost to the attack wave and use that to substitute for many lower-level biters

Or a similar option but more robust:
2) I'm not certain how dynamic the entity definitions are, but it may be possible to 'merge' biters together into a special dynamic-cost unit that's larger than a Behemoth (similar to above), except scale it's HP to reflect the amount of units that went into it and repeat the merge process until the attack wave is under a certain limit of biters,

Either way, the UPS/FPS drops are so frequent that it is a major gameplay disruption.

**Comment by AesSedai** [comment]
We added that mod to see if it helped, and while we did still get major performance drops they seemed to last for a shorter interval.

**Comment by AesSedai** [comment]
Posted this to the [Factorio forums](https://forums.factorio.com/viewtopic.php?f=7&t=50458) for Bugs, Oxyd responded:

> What I'm seeing is that a mod – presumably Rampant – creates some pretty huge unit groups and uses them to attack.
> 
> ![lhghagp](https://user-images.githubusercontent.com/7980540/27809995-bb1a49e6-601a-11e7-9193-d44656e21aa6.png)
> 
> The mod's update time will be low since it only assigns commands to units, and the slowdown then comes from the biters' AI, which is accounted to “entity update”.
> 
> There is some room for optimisation here, but massive swarms will always tax the CPU. So I'll blame Rampant (or some other mod) for this.
> 
> Not a bug.

**Comment by veden** [comment]
As a followup how is your game running in 0.16 of factorio?

**Comment by AesSedai** [comment]
Thanks for the follow up, I haven't actually played a game of 0.16 yet; my group of friends that I usually play with has taken a break from Factorio, but we'll definitely be playing again sometime in the future. I'll leave an update here when we play again!
