### ISSUE TITLE
Fire spitters effect text missing or broken.

### ISSUE THREAD

**Issue by Metallumere** [veden/Rampant#44]
Some text seems to be missing or broken from effect descriptor locales, or just plain undefined.

![As seen here](https://user-images.githubusercontent.com/8814790/112806669-a8d68280-903c-11eb-98af-65ae2f1ecd45.png)

There may be others missing besides fire spitters.
Inferno spitters seem to list almost no effect information.
Suicide biters list explosion damage, but nuclear lists only cluster range, which probably isn't an error but just an inconsistency between them.
All others seem fine at a glance.

This is really minor of course, just figure it's worth documenting here.
However, in the future it may be worth correcting some of this further, since all spitters list acid damage instead of whatever their element is actually supposed to be.

**Comment by veden** [comment]
Fire damage doesn't harm walls, acid is intentional for fire based entities.

**Comment by veden** [comment]
should be fixed in the next version
