### ISSUE TITLE
[Factorio 0.15.27, Rampant 0.15.16] Error on savegame load

### ISSUE THREAD

**Issue by AesSedai** [veden/Rampant#5]
```
Attempt to remote call outside of an event.
stack traceback:
[]__Rampant__/control.lua:349: in main chunk
```

![screenshot_162](https://user-images.githubusercontent.com/7980540/27810070-8b9fa21e-601b-11e7-9894-39993d749832.png)

**Comment by veden** [comment]
Thanks for the report.
This should be fixed in the latest build
