### ISSUE TITLE
Nocturnal mode seems to generate infinite points.

### ISSUE THREAD

**Issue by Deathlymad** [veden/Rampant#53]
Hi,

i have been digging into the code a bit due to kind of "weak behavior of the biters at the current point of our game. Nothing in particular seems wrong but while reading onUnitGroupCreated. 
In the nocturnal mode squads are constantly spawned during the day i assume by factorio, then disbanded by Rampant yielding rampant a bunch of points without ever forming a squad to begin with.

**Comment by veden** [comment]
this should be resolved on the master branch now

**Comment by veden** [comment]
This should be fixed in 2.0.0 that was released yesterday.
