### ISSUE TITLE
Biters are very tiny for some reason 

### ISSUE THREAD

**Issue by iMuhammadMustafa** [veden/Rampant#54]
I disabled all mods and started a new game and they were still at that size 

![image](https://user-images.githubusercontent.com/29302054/140991222-0a382615-aa8b-412d-b259-537741091640.png)

**Comment by veden** [comment]
If Rampant has been disabled then this is something else causing this issue.

**Comment by iMuhammadMustafa** [comment]
Every other mod except Rampant obviously.

**Comment by veden** [comment]
Biters start out smaller in Rampant.
I am misunderstanding the issue?

**Comment by iMuhammadMustafa** [comment]
I aplogize for the late reply. Yes, I thought this size was becasue of a bug. 

So they start that size and get bigger while playing?

**Comment by veden** [comment]
Yes, based on the ending level in the mod settings. The higher the level the stronger and bigger the bugs.
