### ISSUE TITLE
Rampant1.2.0 death mutation crash for older game saves

### ISSUE THREAD

**Issue by garrotte13** [veden/Rampant#55]
ver. Rampant1.2.0
Loading old gamesave (over 70% evo, Rampant1.1.1 played) leads to an error after 10..30 seconds after loading from savefile:

```
The mod Rampant (1.2.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Rampant::on_tick (ID 0)
__Rampant__/libs/BaseUtils.lua:440: attempt to compare number with nil
stack traceback:
	__Rampant__/libs/BaseUtils.lua:440: in function 'processBase'
	__Rampant__/libs/MapProcessor.lua:492: in function 'processNests'
	__Rampant__/control.lua:1073: in function <__Rampant__/control.lua:1032>
```
Tried with different saved games (Rampant1.1.1, Rampant1.0.6 versions). Doesn't occur only for savefiles at early stage (small evolution value, not much biters killed).

**Comment by garrotte13** [comment]
Worked around this crash by temporary code change:
kept those 3 lines only
```
                base.mutations = 0
...
        base.damagedBy = {}
       base.deathEvents = 0
```
played some time, saved and rolled back the deaththreshold comparison code. Problem doesn't occur after it.

**Offtop**: is 3000 deaths enough to survive early game with physical damage only and not being obliterated by phys-resistant factions at evo values 30..50%? For example (probably not a good relation here) I killed 400k biters and 6.5k spawners+others before evo value reaches 80%.

**Comment by veden** [comment]
3000 was my initial guess, but may not be the final value. Open to suggestions, also the adaptation modifier allows for changing that setting by a percentage.

This issue is rooted in bases being recycled before the chunks under the bases control have been destroyed.

**Comment by garrotte13** [comment]
so.. those 3000 killed - are they for particular faction or base (by base I mean a group of nests in a chunk) ? Or it is 3000 for entire game map? In last case 3000 is too small number.

**Comment by veden** [comment]
For the next release I will write up some documentation to go along with everything.
Regional bases are groups of chunks. Each chunk can have many spawners or worms.
Typically on a brand new map, 4 or so regional bases are created that could be something like north, east, south, and west.
Each regional base keeps its own killed count.

**Comment by veden** [comment]
this should be resolved on the master branch now

**Comment by garrotte13** [comment]
Verified.
