### ISSUE TITLE
Blocker. Can't use landfill

### ISSUE THREAD

**Issue by garrotte13** [veden/Rampant#60]
Rampant2.0.0
When laying landfill. It seems to occur at first attempt to do it. So game is blocked now...

Error while running event Rampant::on_tick (ID 0)
__Rampant__/libs/ChunkProcessor.lua:201: attempt to index local 'chunk' (a boolean value)
stack traceback:
	__Rampant__/libs/ChunkProcessor.lua:201: in function 'processScanChunks'
	__Rampant__/control.lua:1006: in function <__Rampant__/control.lua:962>

Update. Is reproduced every time in 100% cases. And on different maps (e.g. with old save with evo 79%).

For some reason doesn't occur at all in Sandbox game.

**Comment by veden** [comment]
https://github.com/veden/Rampant/blob/master/control.lua#L592
https://github.com/veden/Rampant/blob/master/control.lua#L621
change the `true` to `chunk` to unblock your game.

**Comment by garrotte13** [comment]
Thank you! Those changes helped.

**Comment by garrotte13** [comment]
As I understood, it was fixed yesterday. Works fine with synced sources.
