### ISSUE TITLE
Latest Rampant. Too calm biters

### ISSUE THREAD

**Issue by garrotte13** [veden/Rampant#61]
Started a new game with Rampant1.2.0 a week ago. Switched to Rampant2.0.0 eventually. 150% bases frequency, 150% bases size.
20 hours played. Evolution 17% (I set it slow, because new enemies max tier is 10 and tech costs are doubled, but evo is rising anyway).
245 spawners destroyed, over 3000k biters killed.

What makes me worry is **No expansions at all** through all this time. Not even a single one took place. I turned on/off debug logging from time to time - AI State was always Peaceful.

May be something is wrong with the mod. Can it be?

**Comment by garrotte13** [comment]
The only 2 very small expansions were migrations to adjacent chunks with resources in the first few hours of gameplay (coincidentally I switched to Rampant2.0.0 sources after that - but not sure that it is the reason).

**Comment by veden** [comment]
Are you willing to share your save?

**Comment by garrotte13** [comment]
[War1b.zip](https://github.com/veden/Rampant/files/7689256/War1b.zip)

**Comment by veden** [comment]
The next version will have some additional calibration around temperament extremes and attack mixtures.

**Comment by veden** [comment]
and a bugfix that was causing some issues.

**Comment by garrotte13** [comment]
so can I check it after syncing changes or it is not here yet?

**Comment by veden** [comment]
Should be on the master branch.

**Comment by garrotte13** [comment]
Yes,
Checked quickly with old game 79% evo. They are expanding like mad now to siege me. Here is after I purged over 20 nests in the region:
https://imgur.com/a/Sr56CCq

But also in other parts of map near my walls where I wasn't active at all and no pollution was near their nests.

I will check now with legacy Rampant 1.1.1 game I started after finding this issue (comment 0 in this thread) - I was checking old way https://mods.factorio.com/mod/Rampant/discussion/605348bb943f58bba9576e35 and came to conclusion, that Rampant1.1.1 expansions revenge after purging is still as strong as it was in 1.0.6. The only change to game in comment 0 was bases frequencies increased from 150% to 200% and "maximum expansion cooldown" reduced from 45 to 35 minutes (Does Rampant use any of the "Enemy expansion" block's settings when determining settlers/attackers squad behavior?)
Now I need about 16-20 hours to test.

**Comment by garrotte13** [comment]
Here are some test results.
Test steps:
1) Rampant1.1.1 gamesave was taken. This mod version is known to generate enough threat for early game: migrations, revenge expansions on nearest chunks to recently purged ones, etc.
Here is the gamesave for it: 
[Legacy8c.zip](https://github.com/veden/Rampant/files/7698930/Legacy8c.zip)

2) Switched game to Rampant2.0 (synced mod files yesterday). Then all nests were purged in eastern front. It took about 15 minutes.

3) Removed all keepers (gunturrets) in the east. Keeeping only a border of keepers in the south. Made a ride around to find if any new nests appeared - nothing. Returned to base. Turned on logging AI State change.
Pollution cloud touches two bases (in the North-North-East and in the West) - so there was some 'food' for biters to take action besides growing evolution and maybe internal "motives" :-)
Also game difficulty was increased from 1 to 2 - Temperament Rate Modifier and Difficulty Scaling.
Gamesave (approximately) for this moment:
[LegWar3.zip](https://github.com/veden/Rampant/files/7698936/LegWar3.zip)

4) 90 minutes passed. AI state changed to Aggressive, then Peaceful, then again Aggressive, then Migrating, then Sieging.
No new bases till the middle of Sieging stage. No noteworthy attacks on the base - 3 very small attacks from North and 1 from South for all the time (over 1h gameplay, 2 Aggressive states periods and 1 Migration stage.). Took a ride around - no new bases generated by Migration state outside pollution cloud area.
In the middle of Sieging stage THREE new small enemy bases were built. In fresh new places - traces of cut trees are seen.
Gamesave for this final moment:
[LegWar3_testCP6.zip](https://github.com/veden/Rampant/files/7698945/LegWar3_testCP6.zip)

Conclusions:
1. Migration and Aggressive AI stages provide no danger to player (maybe because evo is only 7% ?)
2. Biters do not show affinity to resource areas like they do in Rampant1.1.1 even at game from the very beginning.
3. AI is not so dangerous and revengeful as it is in Rampant1.1.1. But maybe it's ok for evo 7.5%? Because at evo 79% AI looks active enough (didn't play too much that old gamesave, perhaps 20 minutes or less). There were no re-spawning bases for 2-3 destroyed, unlike in Rampant1.1.1.

I can't say that Rampant2.0.0 is less fun. Maybe it is better balanced for players mass. What I missed - endless attack waves (with small groups of course - it's 7% evolution only). Maybe also AI doesn't response strong enough on pollution cloud on bases chunks like it does in Rampant 1.1.1 - difficult to say for sure.

**Comment by veden** [comment]
Migration is primarily for settling resources patches not attacking.
Aggressive only attacks with active/pollution covered nests, so sN:6 on your screenshot. So only 6 spawners would be attacking.
Aggressive AI state has more attack waves per cycle than 1.1.1, so not sure how it would be less dangerous.

Siege AI now moves primarily toward the player instead of player and resources.

**Comment by veden** [comment]
I can revert the rally chance reduction, which causes the endless attack wave loops.

**Comment by veden** [comment]
also I'm not sure what is causing revenge expansions in any of the versions as the vengence squad generation doesn't have a chance to be a settler group.

**Comment by veden** [comment]
something to keep in mind that these builds are on the same version, so the first ~20 minutes the AI is rebuilding state still.

**Comment by garrotte13** [comment]
>Migration is primarily for settling resources patches not attacking.

But point-2 was listed - no resource patches were claimed by v.2.0 biters, unlike Rampant1.1.1 (100% first goal if some resource is in nearby chunks from the very beginning). Maybe need to re-test. Rampant1.2 biters settled on resources 100% too.

>also I'm not sure what is causing revenge expansions in any of the versions as the vengence squad generation doesn't have a chance to be a settler group.

I don't know how, but it almost always happens since v. 1.0.4 or 1.0.5 - please see forum thread I mentioned. A little annoying challenge for very start of the game if map evo factor for killing spawners is 100+. May be it is good we got rid of it (and less cheap biomass for me :-) )

>I can revert the rally chance reduction, which causes the endless attack wave loops.

You know better. Other gamers posted threads about sudden obliteration in the middle of early game - probably most often reason people stopped playing Rampant. I made a habit of building defenses around my base when playing Rampant :-) But it was a pain, especially when temperament points (or how it is properly named) were lost on loading a save and AI went in different direction after unpredictable amount of time. Now with storing it in gamesave players can return and fix their defenses.

>something to keep in mind that these builds are on the same version and it is a full internal state wipe, so the first ~20 minutes the AI is rebuilding state still.

I was purging other enemy bases during those 20 minutes - so maybe this is why they did no revenge expansions... You know better.

**Comment by garrotte13** [comment]
Ok. I'll continue playing with Rampant2.0 normally from the moment LegWar3.zip was saved and see if any new expansions take place when properly defending the territory.

**Comment by veden** [comment]
the expansion map settings are used by Rampant to determine frequency, distance traveled, and group size for settlers.

**Comment by garrotte13** [comment]
Thank you for information.

 I missed last 7 commits you made for some reason when running test today.

**Comment by veden** [comment]
just added some additional commits to add back some of what you feel like is missing.

**Comment by veden** [comment]
this should be the final build short of issues discovered.

**Comment by garrotte13** [comment]
More attacks from out of pollution cloud area now - massive attacks from many bases are visible again. Need to progress further in game (to over 30% evo) to understand how it scales up.

**Comment by garrotte13** [comment]
Does current AI stage influence biters behavior when their neighbour base nests are destroyed? For example do they settle new nests more often near player's turrets area if it is Siege AI state? Or it is co-incidence of vengeance squad built base nearby and too many bases are nearby -> strong fight back.
So far SiegeAI state remains the most active and dangerous one. Migration AI goes without any events at all (may be biters settle somewhere in marginal chunks outside charted map? Resource patches near them remained unsettled). Aggressive AI produce some attack squads (they became noticeable with latest code commits).

**Comment by veden** [comment]
Migration state should be focusing on settling resource patches everywhere.
Otherwise AI stage doesn't currently influence vengence squads or settlers.

**Comment by garrotte13** [comment]
Perhaps everything is ok now. Will report problems at 30-50% evolution if there are any.

**Comment by garrotte13** [comment]
I started new map to test RampantEvolution, played 10h. And want to say, that everything is fine with Rampant2.0.1 (it is most stable for me - I don't have issues and don't want new issues). Biters are active, full fan and so on. Thanks a lot!

**Comment by garrotte13** [comment]
Got understanding of how Migration AI state works - it settles new worms and nests not far away from "base" which sent the squad. It can be the same or adjacent chunk. Really rare +1 more chunk. Squad never goes farther - at least with evo below 40%.

So it ruined my expectations of classic vanilla expansion - not less than 3 chunks away from source nests. And I usually set 3-9 instead of default 3-7 in Enemy section of map settings.

The same about squatting resource patches - they can't be far away from source base.

So far I saw only SiegeAI state to settle far from source, including the case of preferring resource patche chunks near player's base if they are in direction of source enemy base from player's base.
