### ISSUE TITLE
Question. Spawners

### ISSUE THREAD

**Issue by garrotte13** [veden/Rampant#62]
I have a question.
Does Rampant change spawners and worms on new generated chunk ? I mean something like changing spawners and worms locations via for example on_chunk_generated. If New Enemies is On, then probably their properties (size, faction)?
In Warmonger mod creep generating code (originally was 100% from Krastorio2) creep is generated on_chunk_generated . Maybe it is a redundant, resources-consuming call and I should remove it when Rampant is present (or Rampant in new enemies mode only) if spawners are re-created and interface method for creep creation is called for them from Rampant? I ask it because I noticed spawners re-appear when running fast into uncharted areas.

Another similar question:
May be I also should remove creep generation for on_biter_base_built event if Rampant calls interface method for creep deployment when biters settle new nests and worms (also only when Rampant or Rampant New Enemies is detected) ?

**Comment by veden** [comment]
yes for the newly generated chunks, for two reason:
1) because the variations and large number of entities in autoplace is slow
2) I can't control regional variation of factions using pure auto place.

With new enemies enabled, any creep generation would in some since be unneeded because when Rampant takes control of a chunk it will recreated it with the entities it wants including creep.

**Comment by garrotte13** [comment]
I disabled creep generation for on_biter_base_built event when Rampant new enemies is present -> nothing changed.

I disabled creep generation for on_chunk_generated event when Rampant new enemies is present -> no creep for any enemy structure in starting area. But creep is not generated twice anymore when running fast into uncharted areas.

I need to avoid double creep generation for new Warmonger mod features. But I'd like starting area nests to still have creep - seems to me, that it's impossible.

**Comment by veden** [comment]
Everything I wanted to get in for the 2.0 should be on master at this point.
I want to do a final pass on the build and then it will get released.

**Comment by veden** [comment]
let me know if you are having an issues.

**Comment by garrotte13** [comment]
Thanks a lot for help with question in description!
