### ISSUE TITLE
Biters expansion is too rare while migrationAI only extends source enemy bases

### ISSUE THREAD

**Issue by garrotte13** [veden/Rampant#73]
Some kind of general issue description is here
https://mods.factorio.com/mod/Rampant/discussion/61d753f8c324a759c1b6464e

I suppose the problem is with MigrationAI. You wrote in some reply, that MigrationAI behavior prefers resource chunks before any others. Seems like it is too focused on resource chunks. I can't understand if it is the case for nikitasnikitas - can't see if there are resources in problem chunks. For me it is 100% the case - no crazy overlapping occurs in no resource chunks.

Another problem is lack of biters expansion. After playing for many hours in peaceful base construction phase (I mean almost no enemy bases purging and no pollution cloud touching enemy nests) I witnessed only ONE time appearance of three new bases (with 2..7 nests each, in very different parts of map, but all three appeared close to my walls). Unfortunately it happened suddenly, and I missed the AI state name. I'm sure it was not MigrationAI. I suspect it was RaidingAI or with less probability SiegeAI - I can be wrong here.

And third related, minor problem - I suspect, that SiegeAI tactics tries to settle too close to player's base. It doesn't work with appropriate walling of the base, but works well in the very-very beginning when defenses are near player's base center. I can't explain it more. But I see all squads finish their lives with attacking my defenses in SiegeAI phase.

I saw you made some fixes for expansion problem in mod versions 2.1.0&2.1.1, but I'm afraid it didn't help OR it requires a new game.

**Comment by garrotte13** [comment]
I don't see how gamesave will help you with these MigrationAI issues. Overlapping high density spawning occurs during some considerable time (maybe hours). The same about MigrationAI targets of expansion - requires many hours to say that enemy bases are growing in place completely without claiming far away chunks.
Don't know what data I can provide.

**Comment by veden** [comment]
The linked issue is a separate problem from potential migration issues.
The master branch has a mod setting to show settling spots now. If you enable that setting let me know if you are still having problems.
Also something to note is that the default for max builder groups is currently 10. 
You can check the number of active building groups by enabling DEBUG: Print Temperament changes to chat and checking the aB stat.

**Comment by garrotte13** [comment]
It will requires hours of testing. I'll try it out after Rampant will be updated to include FACTO-20 regress fix and after finishing some work on Warmonger - will test in combo.

>The master branch has a mod setting to show settling spots now. 

I don't see this setting anywhere. Can you guide me?

>Also something to note is that the default for max builder groups is currently 10.

I do have other value for max builder groups (unless you are about some internal value, not available in mod settings):
![image](https://user-images.githubusercontent.com/95149904/149742335-02c6e185-7f6c-497d-a018-91e92359306d.png)

**Comment by veden** [comment]
another option for testing is increasing the game speed and forcing the AI into the migration state so that it can be observed.
I would rather not do the debug tracing if it can be avoided just due to time constraints.
`/c game.speed = 10` for 10x
`/rampantSetAIState 5` for setting AI into migration.
Mod setting `AI: Print when settlers start building`
I forgot to push the commits yesterday, so they should be on the master branch now.

**Comment by garrotte13** [comment]
Yes, that's a good idea to try to speed up a little to separate game fun and quick localization of the issue.
I see code changes. Regress fix confirmed.

Do you recommend to test with new game or I may test with previous one (where I tested RampantEvolution, it was started with Rampant 2.0.1) too?

**Comment by veden** [comment]
a new game is not required

**Comment by garrotte13** [comment]
I loaded mentioned gamesave after updating Rampant and it was Migrating AI state. So I watched first 20-30 minutes. 
Doesn't look like something changed in biters behavior. Sorry. They still settle near their homes:
https://imgur.com/a/soK3JxG
https://imgur.com/a/z5IBQeV
https://imgur.com/a/czr3Zl7
https://imgur.com/a/QY4RWns
https://imgur.com/a/fvy7Bz7

SiegeAI:
https://imgur.com/a/o7S4c74
https://imgur.com/a/PB1qJvC - this one settled a little away from his home, but not too far. And not in direction of player's base like I expected for SiegeAI (am I wrong)?
Others settled near homes, far away.

Do you recommend to wait for "new wave"?

**Comment by garrotte13** [comment]
And this is what I described in point-3 of issue thread:
https://imgur.com/a/TjOB5QS
SiegeAI doesn't settle, but attack instead.

**Comment by garrotte13** [comment]
In new MigratingAI situation became better - every 2nd or 3rd settlement took place 3-5 chunks from existing nest/worms.
Is it correct? In changelog you wrote about only 5% settlements to be near nests of origin.

**Comment by garrotte13** [comment]
Started a new map.
And I must admit, that SiegingAI in early game (no wall yet) works very-very good and strong. Hope MigrationAI will be as good. And SiegeAI will still be smart when I wall around...
Settings:
https://imgur.com/a/EpHgRO8

**Comment by garrotte13** [comment]
Biters expand mostly to resources chunks, but other locations also occur. They are less common than "resources claiming" or "in place" base growth, but still do occur:
https://imgur.com/a/RHW5YcX

**Comment by garrotte13** [comment]
I'll close this issue. Enemy expansions do happen (I mean not only Sieging settlements), but:
a) most of them take place not in direction of player's base;
b) claiming chunks on/adjacent to resources is much higher priority;
c) growing base "in place" still occurs very often, but as density was fixed, it looks much better in pre-hive era: https://imgur.com/a/TbgrVyT
d) migration end point for buildes is much more often a point in 1-2 chunks away. Going further is very-very rare, but hopefully still happens (no 100% proof acquired for MigrationAI in particular, because I didn't monitor what AI state type was when such far away expansion occured. Sorry).

I think now it is a good balance with SiegeAI combined. Enemies are strong in terms of expansion whatever AI state makes more sense in it - in the end it doesn't matter. It is fun and thank you for that! :-)
