### ISSUE TITLE
why not enable new enemies by default?

### ISSUE THREAD

**Issue by PlexPt** [veden/Rampant#77]

**Comment by veden** [comment]
Because not everyone wants new enemies and it is significantly harder to play with them.

Do you have a reason for wanting them enabled by default?

**Comment by PlexPt** [comment]
yes，I  have a reason for wanting them enabled by default

**Comment by veden** [comment]
care to explain it?

**Comment by PlexPt** [comment]
Most people play it to make it harder，if not enable new enemies by default，The effect is not obvious

**Comment by veden** [comment]
sure, I will add it to the list

**Comment by PlexPt** [comment]
ok

**Comment by veden** [comment]
This change it in 3.0.0
