### ISSUE TITLE
Friendly Fire

### ISSUE THREAD

**Issue by daxpedda** [veden/Rampant#8]
Small worms and Small spitters, shooting green projectiles, are hitting other Biters, Spitters or Worms.
This issue may apply to other units as well, I just noticed that right at the start.

Only playing with RSO.

If any additional info or help is needed, feel free to ask.

**Comment by veden** [comment]
I think a little friendly fire is ok, but I can make some adjustments to make it not so effective

**Comment by daxpedda** [comment]
Well at the moment if I gather 20 Small Biters one Small Worm kills them all at once with two shots.

**Comment by Thynix** [comment]
Is this with splash damage or do the projectiles have piercing?

**Comment by veden** [comment]
splash damage

**Comment by veden** [comment]
At the moment the neutral biters take splash damage, but the more advanced types have resistances to make friendly fire less effective

**Comment by veden** [comment]
should be an option in the menu to remove most of the splash damage now

**Comment by daxpedda** [comment]
Gonna check it today when I have time.

**Comment by daxpedda** [comment]
"today" - 6 days ago
Sry about that, works perfectly now.
