### ISSUE TITLE
Rampant3.0: error on_unit_group_finished_gathering

### ISSUE THREAD

**Issue by garrotte13** [veden/Rampant#84]
Hello!
The mod Rampant (3.0.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Rampant::on_unit_group_finished_gathering (ID 139)
__Rampant__/libs/ChunkPropertyUtils.lua:577: attempt to index local 'chunk' (a number value)
stack traceback:
	__Rampant__/libs/ChunkPropertyUtils.lua:577: in function 'findNearbyBase'
	__Rampant__/control.lua:834: in function <__Rampant__/control.lua:807>

And a question:
I read in changelog a note, that all biters will disappear when upgrading Rampant from 2.2 to 3.0. As I see only biters disappear - nests are ok. Does it mean that old Rampant2.2 games will be ok after upgrading to 3.0 ?

**Comment by garrotte13** [comment]
Can't validate the fix, because using Rampant3 game save leads with actual mod source code to:

Error while running event Rampant::on_tick (ID 0)
__Rampant__/libs/BaseUtils.lua:272: attempt to index local 'map' (a nil value)
stack traceback:
	__Rampant__/libs/BaseUtils.lua:272: in function 'recycleBases'
	__Rampant__/control.lua:973: in function <__Rampant__/control.lua:956

**Comment by garrotte13** [comment]
The last problem doesn't happen when loading game save of Rampant 2.2 and 2.3. Only for 8days old Rampant3.0 save.

**Comment by veden** [comment]
the upgrade code is looking for a certain global value that needs to be bumped for releases of the same version.

**Comment by veden** [comment]
The master branch has an updated version global, so it would be like you applying 3.0.0 again for the first time.

**Comment by veden** [comment]
a disabled migration function is effectively why you are seeing the error

**Comment by garrotte13** [comment]
I see.
Now loading saved game leads to this error
Error while running event Rampant::on_tick (ID 0)
__Rampant__/libs/AIPlanning.lua:556: attempt to index local 'base' (a nil value)
stack traceback:
	__Rampant__/libs/AIPlanning.lua:556: in function 'processBaseAIs'
	__Rampant__/control.lua:1009: in function <__Rampant__/control.lua:956>

**Comment by veden** [comment]
save I can look at?

**Comment by garrotte13** [comment]
@veden 
Hi! Did you have a chance to look at problem in gamesave? I started new game with Rampant2.3 and noticed eventually, that biters are much less agressive comparing to version 2.2 - they don't expand too much, and there are not many raiding stages (I mean attacks from different bases, including not provoked ones), and not much visibility of SiegingAI. I wonder if it is caused by action points decrease on biters death FACTO-62.
I plan to return to 2.2. or move forward to 3.0 if newer mod version doesn't have blockers.

**Comment by veden** [comment]
The problem should be fixed in the master branch you had with local base being nil should be fixed.

FACTO-62 may be a problem or the ai temperament points may need to be adjusted more.

**Comment by garrotte13** [comment]
yep, validated the fix. Great. Thanks!

>FACTO-62 may be a problem or the ai temperament points may need to be adjusted more.
Before v.2.2 allowing pollution cloud to cover nests led to obliteration by sieging nests. In v.2.3 bases only send attacking squads in accordance with pollution they absorbed. Fortunately reverse to v.2.2 works fine.

Will try to switch to v3.0 and see for a few hours how it goes.

I see two options in mod: 
- Temperament Rate Modifier,
- Difficulty scaling

I increase first option to 1.2 and second to 1.1 to add some "action" when it becomes too boring and evolution is slower than tech progress. Does "Difficulty scaling" decrease the cooldown between units born by nests under my attacks? If yes, then it could be great to put it in a separate option - so player could avoid increasing it while increasing total strategic activity of enemies.

Another question:
I noticed in v.2.3 and 3.0 more often AI behavior when it sends units chaotically from all nearby bases (without making tight squads, but just an endless mass of single/paired units) - sometimes it gives some fun, sometimes such time-distributed biters incoming is too easy to defense against unlike big densely packed "armies". Is it called "Onslaught" ?

**Comment by veden** [comment]
v2.3 would potentially have incomplete functionality.

Temperament Rate is how quickly the AI will change states. Difficulty Scaling is how quickly the AIs will get points to spend on actions.

So increasing Difficulty scaling will decrease the cooldown indirectly

Onslaught is an uncapped number of squads in a given amount of time with increased point growth.

Not sure about single/paired unit groups being sent, I would need to look into it.

**Comment by veden** [comment]
Do you have a save with the single/paired unit groups issue?

**Comment by garrotte13** [comment]
No, I don't. I thought it was a new feature in AI behavior, which has its selection prioritity increased in v.2.3. If I see it in v.3.0 I'll make a gamesave.

**Comment by garrotte13** [comment]
> FACTO-62 may be a problem or the ai temperament points may need to be adjusted more.

I set Difficulty Scaling to 1.3 and biters do expand.
I didn't see any revenge attacks or revenge nestings when destroying parts of bases - looks like another sequence of FACTO-62. But maybe it's just because I didn't play too much (I tested for 70 min with settlers start building and stage change hints set as On at evolution 4..5%).

**Comment by garrotte13** [comment]
Closing this issue as problems in first two comments are fixed.

**Comment by garrotte13** [comment]
> I didn't see any revenge attacks or revenge nestings when destroying parts of bases - looks like another sequence of FACTO-62. But maybe it's just because I didn't play too much (I tested for 70 min with settlers start building and stage change hints set as On at evolution 4..5%).

After several hours of gameplay with Difficulty Scaling = 1.2 I see no problems with it. Biters expand a lot under pollution cloud, settle nests both near my defenses and on half way from the source base. In different directions, not only on straight line between centers of their my bases.
So everything is very live and active on difficulty 1.2, not less than Rampant2.2 with difficulty 1.1 is.
