### ISSUE TITLE
Rampant3.0. Turret gun fire sounds are absent often

### ISSUE THREAD

**Issue by garrotte13** [veden/Rampant#89]
New enemies are On of course.

Typical steps to reproduce:
Install a row (let it be 5 turrets for example) of usual vanilla gun turrets near enemies. You can do it near base, but can do it near a squad of biters (common biters in early game). 

Actual results: 
1. sound of one turret installed instead of multiple such sounds. Like only one turret is installed.
2. sounds of rare gunfire, such rare like someone is using pistol (It is still a sound of gunturret, not vanilla pistol sound. But a single shot sound, not automated gunfire burst sounds mix).
3. An often situation of total silence inbetween biters' sounds like I'm already dead or my PC sound system is broken. Like someone turned off sound. Only biters screams (be it biters, spitters or falling worms) in total silence.

Expected results:
1. vanilla sound of 3-5 installed buildings - I mean 3..5 repeated sounds
2. automated gun burst fire sound
3. total sound hell is expected - 5 turrets firing, worms firing, everyone is screaming, etc like I'm watching Alien movie. :-)

Can it be caused by fixing enemies sounds?

**Comment by garrotte13** [comment]
I don't know if the original sound fix works. I hear killed falling worm sound so often now like it was really missing in previous mod versions, but maybe it's because nothing else is making noise. Only falling worm in total silence :-(

**Comment by garrotte13** [comment]
I didn't install/change vesions of any other warfare mods. Only Rampant 3.0 was updated from Mar 31 version to 42c4f4c623fc8679da58fac5ad79ebaebec64e77 sources revision.

**Comment by garrotte13** [comment]
I can try to make a video if you need one.
Issue is not a pleasant one. Feeling like I'm deaf sometimes.

**Comment by veden** [comment]
Do you have a save?

**Comment by garrotte13** [comment]
It's strange, but I can't reproduce the problem today - tried many times. Probably it is some Factorio issue in some circumstances. Maybe less physical RAM available on PC or multiple game re-starts or other factors. I don't have any ideas now. I didn't change anything in Factorio Settings before of after problem.
I'm sorry.

**Comment by garrotte13** [comment]
Oh, my fault. I made a branch on revision before sounds fix yesterday and forgot about. Reverted to revision after sounds fix and reproduced (it happens in 30-40% situation. Will try to make gamesave before that very moment, but not sure if it is not a complete random).

**Comment by veden** [comment]
Are you using any mods aside from Rampant?
How many things are around you that are making noise?
It looks like factorio has a max number of sounds that can play all at once, it is something like 50 and is configurable in a hidden menu inside factorio

**Comment by garrotte13** [comment]
You could see mods list in a gamesave in other issue thread. I'm playing only one game at a time :-)
List of mods that produce or MAY produce (I'm not sure) sounds in this issue situation:
- Rampant
- Bullet Trails (not sure, I'll check it code now...)
- Rampant Arsenal (not sure, because it's the game stage with vanilla turrets)

that is all! Warmonger mod produces sounds only when harvesting creep and I'm not doing it when problem occurs.

So... number of mods is very-very short.

**Comment by garrotte13** [comment]
Ah, Alien Biomes adds sounds for walking. But as I suspect it replaces walking sounds for tiles, not increases a total number of sounds. Can't say for sure.

**Comment by garrotte13** [comment]
> How many things are around you that are making noise?

It's difficult to say. It's a battle somewhere near biters nests. Usually there are many things: biters, worms, nests, my character, my gunturrets. But I do not see any abnormal number of sound-producing issues.

> It looks like factorio has a max number of sounds that can play all at once, it is something like 50 and is configurable in a hidden menu inside factorio

I searched Factorio forums for this problem yesterday when suspecting some internal Factorio issue - didn't find anything. If you want me to find and fix the issue, please give me an idea where I can start.

**Comment by garrotte13** [comment]
hm, found a similar issue
https://forums.factorio.com/viewtopic.php?f=49&t=101651&p=566560#p566560

**Comment by garrotte13** [comment]
hm, moderators deleted my post about this problem in that thread. Second time I see some ... (not clever people) doing it there.

**Comment by garrotte13** [comment]
Tried to increase that value from 50 to 70 - didn't help.

**Comment by garrotte13** [comment]
I tried to change two lines to remove added sounds
line 296 and 297 in BiterUtils.lua
        working_sound =  nil,
        walking_sound = nil,
but it didn't help much. And also I still hear "chitchat" biters sounds. As I see there are many more lines to be changed to "fix" it back.

If I simply switch to revision 9e059cd8beac16c726537fc143541c8363b8ccfe , then problem disappears and biters "chitchat" too. I hear only when they do bite me or land projectiles very near me.
Honestly speaking these sounds do make sense only for fauna lovers and with no background music. I never ever have noticed this "chitchat" in vanilla (probably I played with music all the time while these sounds are of very low volume level).
While abscense of **buildings installation** sounds, missing **bullets magazines inserting** or **gunturret firing** do really hurt gameplay - it causes some animation VS sound perception conflict in player's mind.

I can try to rise a ticket in Factorio forums if you want, but I'll need detailed info for that. I don't know if they care to read mod's source code, especially such complicated as Rampant has. But giving your commit changelog should simplify the quest for them.

**Comment by veden** [comment]
I can reproduce this in vanilla, 2.2.0, and 3.0.0. I consider this to be a limitation of the factorio engine.

**Comment by garrotte13** [comment]
Do you suggest to reproduce the problem with no Rampant and send it to Factorio developers?

**Comment by veden** [comment]
You are welcome to create a reproduction of the problem and give it to the Factorio developers.
According to the forum post you linked, they are aware of the problem and have said they will fix it at some point.

**Comment by garrotte13** [comment]
Tried one more time with sounds fix commit - game is not playable unfortunately. I don't know why other players don't complain (maybe they love fauna more than turrets building and weapon firing sound - I don't know).
The only way to play Rampant now is this:
![image](https://user-images.githubusercontent.com/95149904/168514617-acfde088-d578-4fd3-baf5-cc1989247335.png)

**Comment by garrotte13** [comment]
I'll try to find time to turn off all mods and try to reproduce the problem in vanilla. But I suppose that for vanilla it's a very rare situation - it doesn't produce enough nests per square kilometer -> not enough spitters/biters to walk around and defend its low-density bases. Therefore even if I succeed with repro Wube guys won't treat this critical issue with appropriate attention I'm afraid. There are several critical bugs in Factorio they never fix, because it happens too rarely (or too short game stage, like total f*ckup they made with electric poles blueprints in pre-bot game era - they don't care, because one can't has the problem with construction bots) and this one will be plus one to that mass. :-(

**Comment by garrotte13** [comment]
Factorio 1.1.62 has a new sounds mixing engine code inside... maybe they fixed this critical issue...

**Comment by garrotte13** [comment]
No, unfortunately problem was not fixed.

**Comment by garrotte13** [comment]
Tested with only "working" sounds nulled - problem disappears, while upcoming hordes footsteps are heard and all turret sounds in place.

I believe Wube are aware of many limitations their game engine has and don't want to improve it - to keep it simple and very high quality piece of software.
