### ISSUE TITLE
Crash when placing landfill on water in latest version of Factorio

### ISSUE THREAD

**Issue by kirazy** [veden/Rampant#9]
When placing a landfill tile to fill in some water, Rampant throws an error. Removing Rampant from the enabled modlist allows the landfill to place successfully.

https://i.imgur.com/mnW7nKg.jpg

Testing with only Rampant (and a creative mod) enabled, on a clean, new world throws the exact same error.

For the clean, fresh world with only Rampant and a creative mod:
Error log: https://pastebin.com/cpfnCjtt

**Comment by CyaNox** [comment]
#10 should fix this ;)

**Comment by veden** [comment]
I will be posting a build here shortly. Thanks CyaNox
