### ISSUE TITLE
Mutations

### ISSUE THREAD

**Issue by garrotte13** [veden/Rampant#94]
Is algorithm of mutation due to damage type X somehow related to resistance? With evolution 30% I see mutations caused by physical damage to generate Electric, Acidic factions - I suppose they are even less resistant to phys damage, than Common faction.

**Comment by garrotte13** [comment]
Another question: if I load from game save just before mutation takes place, then another mutation occurs: to other faction and it maybe not "due to damage type X", but "Random" one. Isn't this random seed stored in globals->gamesave now?

**Comment by veden** [comment]
all the random calls should be using a seeded generator from the lua api. The only other option I have is to use the xor random generator I have code in the mathUtils.

Without a save it is hard to say, but my guess would be that the faction was already Electric and mutated to a primary of Acidic from the physical damage otherwise I don't believe electric can be rolled from physical damage

**Comment by garrotte13** [comment]
> all the random calls should be using a seeded generator from the lua api. The only other option I have is to use the xor random generator I have code in the mathUtils.

The fact is that I have a game save after loading and waiting a few minutes a mutation occurs, but always different. Just tested it now with loading and doing nothing - no mutation occurred at all :-) Heh, really different random generator seed value every time...

> Without a save it is hard to say, but my guess would be that the faction was already Electric and mutated to a primary of Acidic from the physical damage otherwise I don't believe electric can be rolled from physical damage

Unfortunately I didn't save a game after mutating into Electric. Only before mutation and after mutating into Acid. Frankly speaking I don't get why Acid faction is good selection for mutation "due to damage type physical".
Concerning previous type of faction - mod doesn't print it in the message. It only gives info about outcome faction, not the incoming one. And by the way - "World:Max mutations per faction" is set to 1. But I saw acid faction biters in this game before (they can be found on newly  discovered chunks). Therefore no 100% clarification can be given here. Mystery.

**Comment by garrotte13** [comment]
Ok. My first question is probably wrong. I should dismiss it as no game save is available and I after some tries with save before mutations I'm not able to reproduce Electric faction - I got no mutation in next 20 minutes most of times and mutation to Acid / Fast biters factions - and it happens not at some exact time, but with great variability of time passed value.
And probably answer to my second question is random seed isn't the only factor. Depending on following player moves resulting mutation event (it's time and outcome) is different for every playthrough of the same game save.

**Comment by garrotte13** [comment]
I suppose Electric were generated as effect of type damage = Random. Therefore no issue with it.
Concerning other (acid to be less defended against physical damage than Common faction is) - it is a minor problem. Forget it.
