### ISSUE TITLE
can't start factorio with Rampant 3.1

### ISSUE THREAD

**Issue by garrotte13** [veden/Rampant#96]
Hi,

after updating mod I get this error on factorio application run 
![image](https://user-images.githubusercontent.com/95149904/167343664-10cb0508-2b6f-4483-8d2a-c8fbc93cdc70.png)

Trying to understand what I did wrong...

**Comment by veden** [comment]
no idea, a save probably would help.

**Comment by garrotte13** [comment]
Save can't help here, because it happens long before. Game application doesn't start - gives this error on application load when loading all mods, prototypes, etc.
I'll do a clean check now

**Comment by garrotte13** [comment]
Hm, I switched from github folder to released Rampant_3.1.0.zip and got the same error. I see only two ways out now: I reset mod settings or there's really some problem in mod on your side. Sorry.

**Comment by garrotte13** [comment]
Resetting mod settings fixed the problem! Weird... maybe it didn't like some value of Enemy Random Seed.

**Comment by garrotte13** [comment]
:-((((
After returning all values manually in StartUp settings for Rampant I encounter this  error again. There's some issue in mod code.

**Comment by garrotte13** [comment]
Tried to change enemy random seed to some smaller valued - didn't help.
Here is the full list of changed settings:
Units effected by Tiles - changed
Revert Enemy Map Color - changed
Corpse FadeOut time = 90
Disallow Friendly Fire Splash Damage = True
Random Seed = 9012016 (but it's not the cause as I checked)
Enemy Variations = 7
Enemy End Tier = 10
Unit Nest Breath Air = False
Spitter Damage Scaler = 1.2
Worm Damage Scaler = 1.1
Hive Healing Scaler = 1.2

and for all factions I changed in color hexes  last number from 33 to 93

**Comment by garrotte13** [comment]
![image](https://user-images.githubusercontent.com/95149904/167351051-2f16fa4b-ee16-4739-9b9d-2ed837519ce5.png)
looks like spawningcooldownend misses value for last tier. Probably no one will be able to run factorio with max tier = 10.

**Comment by garrotte13** [comment]
Added 867 to array and it fixed the problem.

**Comment by garrotte13** [comment]
Your fix worked.
