### ISSUE TITLE
No New Hives in already generated chunks

### ISSUE THREAD

**Issue by garrotte13** [veden/Rampant#98]
To continue https://github.com/veden/Rampant/issues/95
a similar question:
Will hives appear in generated chunks during Migration or SiegingAI at some point in time? I waited for many hours after evo exceeded 30% and I can't see a single hive to be built during expansions. New nests have been built in resource chunks, but those are just biters spawners. No hives. I can't say that a lot of new structures appeared, but there was enough place for them to appear if talking about entire generated map.

Or is it by design in Rampant v3 that player has to conquest more territories to get to new generated resource containing chunks to encounter hives?
Or maybe the chances now are very small?
In previous issue thread I see that structures upgrade never generates hives - Ok. But what about new settlements?

**Comment by garrotte13** [comment]
Looked around in god mode - no hives at all.
It makes me think about two possible reasons:
a) hives do appear only for particular expansion activity with special requirements. For example migration to new chunk with no enemy buildings and with resources in that chunk. Player doesn't have such chunks for obvious reasons - when evo exceeds 30% all chunks with resources are populated OR make up part of player's defended territory.
b) some issue in mod code.

None of these two existed in Rampant 2.*.

Here is my gamesave as a proof (pls ignore other mods except BZ ones - they add new resources, so without them you'll get incorrect resources patches locations):
[Tung3d_NoHivesFound.zip](https://github.com/veden/Rampant/files/8696980/Tung3d_NoHivesFound.zip)
The moment of save shows internal small migration producing only one worm - probably structures are already placed too dense there. But look around and see that hives are only in far regions, that probably were in not generated chunks by the moment my evo exceeded 30%. If you want I can try to find the gamesave just before I discovered those chunks, so you or me can test what happens if evo is over 30% BEFORE vs AFTER they generated.

**Comment by garrotte13** [comment]
Do I miss some release notes or other info about changed behavior? As I see no hives are created during biters migration. Evolution value is over 45%.

**Comment by veden** [comment]
Nothing should have changed for hive creation.

When using your save, I see new hives being generated in resource patches.

**Comment by garrotte13** [comment]
You see hives only in chunks generated after I reached evolution 30%.
Ok, I cleaned a big area with 2 resource patches and started waiting. Actual evo = 50%. Should be a lot of hives. And then my only problem is overpopulated chunks by the moment evolution exceeds 30% - no place to build a hive :-)
Let's see...

**Comment by garrotte13** [comment]
Spent two hours on pure test game - you're right, one hive has appeared in SIX (!!!) resource patch containing chunks. In Rampant 1 and Rampant 2 I saw at least two hives appearing in the same circumstances.

Looks like in general hives became much rare due to strict rules of spawners building to avoid overpopulation problem in older mod version and due to microscopic chance of hive in chunks with no resources.

**Comment by veden** [comment]
I can add something to the todo list for a small chance of structure upgrades switching to hive if on a resource patch and under some threshold for the number of hives already in the chunk

**Comment by garrotte13** [comment]
It's up to you how to correct those chances in the end. Be it upgrade or maybe still a possibility for hive to appear in new place after you fixed overpopulation of resouce chunks and reduced hives chance in no-resource chunk.
Maybe you have some enemy base related info at the moment and can calculate if there are existing spawners of this base on resource chunks and therefore a new spawner can be a hive because of it, even in no-resource chunk...

**Comment by garrotte13** [comment]
Hi!
After switching to recent Rampant version 3.1.2 **AND** after new faction mutation occurred new hives appeared:
![image](https://user-images.githubusercontent.com/95149904/174246711-b247229b-ec4f-4140-8ca1-f88465282425.png)

I don't know what helped here. Usually after mutation next migrationAI phase produces a lot of new nests with new faction type. But now they spawned almost over old nests and worms looks like they are ignoring resource chunks overpopulation fix you did for Rampant 3.0. As this happened only in one place - where new faction made a lot of nests/worms I don't know if that is a fix.

Also I found one new hive in no resource chunk. Thank you for that! :-)

**Comment by garrotte13** [comment]
Also noticed in this version:
a) that enemies are less crazy about resource chunks (don't settle there with every opportunity).
b) nests started to overlap again (like before overpopulation fix - https://mods.factorio.com/mod/Rampant/discussion/61d753f8c324a759c1b6464e). I have Shrink Nests and Worms set as On.

**Comment by veden** [comment]
a) To be expected with this version
b) The picture you shared is significantly less than the thread you linked. Do you have a new picture of over population similar to the thread you linked?

**Comment by garrotte13** [comment]
a) Yep, noticed it in changes;
b) No, I didn't say that problem returned. It needs a long play with enemy occupied chunks to see how it will go. I don't have it. All I want to say that immediately after that particular issue fix nests stopped to collide at all and now they do sometimes...
Also I took old save (Rampant 3.1.1) and found similar nests tight placement - probably nothing changed in recent revisions. Sorry.

**Comment by garrotte13** [comment]
In new game everything is fine.
